version: '3.9'

services:
  ceres_frontend_docker:
    container_name: ceres_frontend_container
    image: ceres_frontend_image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
