services:
  ceres_frontend_docker:
    container_name: ceres_frontend_container
    image: ceres_frontend_image
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TZ: America/Asuncion
    ports:
      - 4500:80
    env_file:
      - ./backend.env 
    
    command:  # Obtiene la IP local, la guarda en backend.env, 
              # reemplaza las variables en config-formato.json con valores dinámicos y 
              # genera el archivo config.json en docker, en la direccion /usr/share/nginx/html/assets/ antes de iniciar el servidor.
                  # Para obtener ip publica de la maquina: NOMBRE_SERVIDOR=$(curl https://ipinfo.io/ip)
            /bin/sh -c "
             export NOMBRE_SERVIDOR=$(ip route | awk '/default/ {print $3}') && \echo -e "\NOMBRE_SERVIDOR="$NOMBRE_SERVIDOR >> backend.env;
            
             envsubst '$${NOMBRE_SERVIDOR},$${PUERTO_BACKEND}' 
              < /usr/share/nginx/html/assets/config-formato.json > /usr/share/nginx/html/assets/config.json 
              && exec nginx -g 'daemon off;'
            "